name: human_avatar
description: A Flutter package for both ios and android creating animation text to speech.
version: 0.0.2
homepage: https://github.com/MobilyteApps/human_avatar
repository: https://github.com/MobilyteApps/human_avatar
issue_tracker: https://github.com/MobilyteApps/human_avatar/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:



  plugin:
    platforms:
      android:
        package: com.example.human_avatar
        pluginClass: HumanAvatarPlugin
      ios:
        pluginClass: HumanAvatarPlugin
      linux:
        pluginClass: HumanAvatarPlugin
      macos:
        pluginClass: HumanAvatarPlugin
      windows:
        pluginClass: HumanAvatarPluginCApi

